title:            Daniel A. Koepke
tagline:          I build great software that people love.
description:      Daniel A. Koepke is a software engineer with over 10 years experience building software.
#Comment out url when working locally to resolve base urls correctly
url: http://dkoepke.github.io

# Owner/author information
owner:
  name:           Daniel A. Koepke
  avatar:         avatar.png
  bio:            "I build great software that people love."
  email:          dkoepke@gmail.com
  twitter:        spoondan
  github:         dkoepke
  instagram:      spoondan

# Links to include in top navigation
# For external links add external: true
links:
  - title: Resume
    url: /resume
  - title: LinkedIn
    url: http://www.linkedin.com/pub/daniel-koepke/19/217/a7a
    external: true
  - title: TIL
    url: /til
  - title: Github
    url: https://github.com/dkoepke
    external: true

collections:
  til:
    output: true
    permalink: /til/:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post-no-feature"
  - scope:
      path: ""
      type: "til"
    values:
      layout: "til-post"

timezone:    America/Los_Angeles
future:      true
markdown:    kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "vendor"]
